hello1/api/urls.py
from django.db import router
from django.urls import path,include
from hello1.api import views
from rest_framework.routers import DefaultRouter

router=DefaultRouter()
router.register('crud',views.UserViewSet,basename='user')
router.register('crud1',views.ProductViewSet,basename='product')


# This api url 
urlpatterns=[
    path('',include(router.urls))
]

memory_management1/urls.py
from django.contrib import admin
from django.urls import path,include
from hello1 import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('signup/',views.sign_up,name='signup'),
    path('login/',views.log_in,name='login'),
    path('logout/',views.log_out,name='logout'),
    path('addshow/',views.add_show,name='addshow'),
    path('updatebook/<int:id>',views.updatebook,name='updatebook'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('books/',views.user_books,name='books'),
    path('api/',include('hello1.api.urls'))      # This is api url which is created in hello1 folder
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   # This settings for image upload from the data base

hello1/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager,UserManager
from django.utils.translation import gettext_lazy as _

# Create your models here
# This class inherit basemanager
class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, first_name, last_name, mobile, **extra_fields):
        if not email:
            raise ValueError('Email must be provided')
        if not password:
            raise ValueError('Password must be provided')
        
        user=self.model(
            email = self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            mobile=mobile,
            **extra_fields
        )
        
        user.set_password(password)
        user.save(using=self._db)
        return user
    
     # This function for the user creation and we don't need give permission and superuser and staff
    def create_user(self, email, password, first_name, last_name,mobile, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, first_name, last_name,mobile, **extra_fields)
    
    
# This function for creating superuser and we should give the permissin of sueruser and staff
    def create_superuser(self, email, password, first_name, last_name,mobile, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, first_name, last_name,mobile, **extra_fields)
        

# The purpose of this model is to change login field means we change username field at the replacement of email  

class User(AbstractBaseUser,PermissionsMixin):
      # AbstractBaseUser has password,last_login,is_active by default
      
      email=models.EmailField(db_index=True,unique=True,max_length=254)  # Email should be unique
      first_name=models.CharField(max_length=150)
      last_name=models.CharField(max_length=150)
      mobile=models.CharField(max_length=40)
      address=models.CharField(max_length=350)
      
      is_staff=models.BooleanField(default=False)   # it must be needed
      is_active=models.BooleanField(default=True)
      is_superuser=models.BooleanField(default=False)
      
      objects = CustomUserManager()

      USERNAME_FIELD = 'email'                      # it must be needed to change usernamefield
      REQUIRED_FIELDS = ['first_name','last_name','mobile']
      
      class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

# This model is created table for our product data
class Product(models.Model):
    name=models.CharField(max_length=50)
    auth_name=models.CharField(max_length=50)
    price=models.IntegerField(default=250)
    description=models.CharField(max_length=800,default='',null=True,blank=True)
    image=models.ImageField(upload_to='uploads/products/')

hello1/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django import forms
# from django.contrib.auth.models import User
from .models import User,Product
from django.utils.translation import gettext_lazy as _

# This class is for signnup form which is provide by django and we have to customize it for better design

class SignUpForm(UserCreationForm):
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Password Confirm',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['first_name','last_name','email','mobile','address']   # Change the username field as email field
        labels={'email':'Email'}
        widgets={'email':forms.EmailInput(attrs={'class':'form-control'}),
                 'first_name':forms.TextInput(attrs={'class':'form-control'}),
                 'last_name':forms.TextInput(attrs={'class':'form-control'}),
                 'mobile':forms.TextInput(attrs={'class':'form-control'}),
                 'address':forms.TextInput(attrs={'class':'form-control'}),
                 }
        

# This class is for login form which is provide by django and we have to customize it for better design        
class LoginForm(AuthenticationForm):
    # email=UsernameField(widget=forms.EmailInput(attrs={'autofocus':True,'class':'form-control'}))
    password=forms.CharField(label=_('Password'),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'})) 
    class Meta:
        model=User 
        fields=['email']
        labels={'email':'Email'}
        widgets={'email':forms.EmailInput(attrs={'class':'form-control'}),
                 
        }


# This class is a bookentry form for our staff user,they can fill all the information about book
# we have to customize it for applying external classes
class Bookentry(forms.ModelForm):
    class Meta:
        model = Product
        fields=('name','auth_name','price','description','image')
        widgets={'name':forms.TextInput(attrs={'class':'form-control'}),
                'auth_name':forms.TextInput(attrs={'class':'form-control'}),
                'price':forms.NumberInput(attrs={'class':'form-control'}),
                'description':forms.TextInput(attrs={'class':'form-control'}),
                'image':forms. ClearableFileInput(attrs={'class':'form-control'}),
                }

hello1/api/views.py
from html5lib import serialize
from hello1.models import User,Product
from hello1.api.serializers import ProductSerializer, UserSerializer
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticatedOrReadOnly

class UserViewSet(viewsets.ModelViewSet):
    queryset=User.objects.all()
    serializer_class=UserSerializer
    authentication_classes=[SessionAuthentication]
    permission_classes=[IsAuthenticatedOrReadOnly]
    

class ProductViewSet(viewsets.ModelViewSet):
    queryset=Product.objects.all()
    serializer_class=ProductSerializer
    authentication_classes=[SessionAuthentication]
    permission_classes=[IsAuthenticatedOrReadOnly]

hello1/views.py
import django
from django.shortcuts import render
from .forms import SignUpForm,LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import Bookentry
from .models import Product

# Create your views here.
# This function for home 
def home(request):
    return HttpResponseRedirect('/books/')

def sign_up(request):
    if request.method == 'POST':
        fm = SignUpForm(request.POST)
        if fm.is_valid():
            # nm = fm.cleaned_data['username']
            # fn = fm.cleaned_data['first_name']
            # ln = fm.cleaned_data['last_name']
            # em = fm.cleaned_data['email']
            # pm = fm.cleaned_data['password1']
            # pm2 = fm.cleaned_data['password2']
            # reg = User(username=nm, first_name=fn, last_name=ln, email=em,password1=pm,password2=pm2)
            # reg.save()
            fm.save()
            messages.success(request, 'Account created successfully')
    else:                                                    # This is for get request
        fm = SignUpForm()
    return render(request, 'hello1/signup.html', {'form': fm})
    

# This function is for login user/superuser
def log_in(request):
 if not request.user.is_authenticated:            # user not already login
    if request.method == 'POST':
        fm = LoginForm(request=request, data=request.POST)
        if fm.is_valid():
            ename = fm.cleaned_data['username']
            upass = fm.cleaned_data['password']

            user = authenticate(email=ename, password=upass)
            if user is not None:
                login(request, user)
                if request.user.is_staff == True:        # this condition is for staff/admin user 
                    return HttpResponseRedirect('/addshow/')  # only staff user can redirect this path
                else:
                    return HttpResponseRedirect('/books/')  # for loacal user (no staff permission)
                         
    else:                                    # This is get request
        fm = LoginForm()          
    return render(request, 'hello1/login.html', {"form": fm})  # login form will show
 else:
     if request.user.is_staff==True:
        return HttpResponseRedirect('/addshow/')  # if satff/admin has already login then this condition will active
     else:
         return HttpResponseRedirect ('/books/')   # for already login local user
 
 

def log_out(request):
    logout(request)
    return HttpResponseRedirect('/login/')  # user will go to the login page after logout


#this function is for adding new book an show item 

def add_show(request):
    if request.user.is_staff == True:    # only staff/admin user can add/show books 
    
        if request.method == 'POST':        # if request is post then this condition will active
            fm = Bookentry(request.POST,request.FILES)     
            if fm.is_valid():
                nm=fm.cleaned_data['name']
                an=fm.cleaned_data['auth_name']
                pr=fm.cleaned_data['price']
                im=fm.cleaned_data['image']
                ds=fm.cleaned_data['description']
                reg=Product(name=nm,auth_name=an,price=pr,description=ds,image=im)
                reg.save()
                fm=Bookentry()         
            # we can use this method also fm.save()
        else:    
            fm = Bookentry()               # This is get request books entry form will show
        stud = Product.objects.all()      # All objects are retrive by this query set
        return render(request,'hello1/addshow.html',{'form':fm,'stu':stud})  
    else:
        return HttpResponseRedirect('/books/')    # this is for local user 


# This function delete objects and only staff/admin can do this 
def delete(request,id):
    if request.user.is_staff == True:
        if request.user.is_authenticated:
          if request.method == 'POST':
            
             pi=Product.objects.get(pk=id)
             pi.delete()
             return HttpResponseRedirect('/addshow')
        else:
            return HttpResponseRedirect('/login/')      
         
    else:
        return HttpResponseRedirect('/books')     

#update book
# def updatebook(request,id):
#         pi=Product.objects.get(pk=id)
#         # fm=StudentRegistartion(instance=pi) 
#         return render(request,'store/updatebook.html',{'pi':pi})

# This function will update the objects information and only staff/admin can do this
def updatebook(request,id):
    if request.user.is_staff == True:
        if request.method =="POST":
            pi=Product.objects.get(pk=id)
            fm=Bookentry(request.POST,request.FILES,instance=pi)
            if fm.is_valid():
                fm.save()
        else:
            pi=Product.objects.get(pk=id)
        fm=Bookentry(instance=pi) 
        return render(request,'hello1/updatebook.html',{'form':fm})
    else:
        return HttpResponse('soory you are not Authorize') 
    
# This function is for our user and it will only show books

def user_books(request):
    # if request.user.is_authenticated:
    books=Product.objects.all()
    return render(request,'hello1/books.html',{'books':books})

hello1/templates/hello1/addshow.html
{% extends 'hello1/base.html' %}
{% block content %}
<div class="container-fluid mt-3 mx-1">
    <div class="row">
        <div class="col-lg-3 mx-auto">
            <h4 class="text-center alert alert-primary">Add new Book</h4>
            <form action="" method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                 {{form.label_tag}} {{form}} {{form.errors|striptags}} <br><br>
                <input id="button"  type="submit" class="btn btn-success" value="Add">
            </form>
        </div>
        <div class="col-sm-8 ">
            <h4 class="text-center alert alert-primary">List of Book</h4>
            {% if stu %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Author</th>
                        <th scope="col">Description</th>
                        <th scope="col">Price</th>
                        <th scope="col">Image</th>
                    </tr>
                </thead>
                <tbody>
                    {% for st in stu %}
                    <tr>
                        <th scope="row">{{st.id}}</th>
                        <td>{{st.name}}</td>
                        <td>{{st.auth_name}}</td>
                        <td>{{st.description}}</td>
                        <td>{{st.price}}</td>
                        <td><img class="rounded float-right" width="140px" height="110px" src="{{st.image.url}}"
                                alt="Card image cap"></td>
                        <td> <a id="button"  href="{% url 'updatebook' st.id %}" class="btn btn-warning">View</a>
                            <form class="d-inline" action="{% url 'delete' st.id %}" method="post">
                                {% csrf_token %}
                                {% if perms.store.delete_product %}
                                <input id="button"  class="btn btn-danger" type="submit" value="Delete">
                                {% endif %}
                            </form>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

hello1/templates/hello1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Bookshop</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Signup</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="container">

      </div>
      {% block signup %}    
      {% endblock signup %}
      {% block login %}    
      {% endblock login %}
      {% block content %}    
      {% endblock content %}
</body>
</html>

hello1/templates/hello1/books.html
{% extends 'hello1/base.html'%}
{% block content %}
<body>   
    <main>  
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for books in books %}
            <div class="col">
              <div class="card shadow-sm">
               <img src="{{books.image.url}}" alt="">
    
                <div class="card-body">
                  <span class="'fw-bold">{{books.auther_name}}</span>
                  <p class="card-text">{{books.description}}</p>
                  <span class="fs-5">Rs. {{books.price}}</span>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    </div>
                  
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          </div>
        </div>
      </div>
    
    </main>       
      </body>
{% endblock content %}

hello1/templates/hello1/login.html
{% extends 'hello1/base.html' %}
{% block login %}
<div class="container my-5">
    <div class="row">
    <div class="col-sm-6 offeset-sm-1">
        <form action="" method="POST" novalidate class="shadow-sm p-5">
            {% csrf_token %}
            {% for fm in form %}
               {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>  <br> <br>
             {% endfor %}
             <input type="submit" class="btn btn-primary mt-4" value="Login">
             <br>
           {% if form.non_field_errors %} 
           {% for error in form.non_field_errors %}
           <p class="alert alert-danger my-3">{{error}}</p>
           {% endfor %}
           {% endif %}
        </form>
        {% if messages %}
        {% for msg in messages %}
        <p {% if msg.tags %} class="alert alert-{{msg.tags}}" {% endif %}>{{msg}}</p>
        {% endfor %}
        {% endif %}
    </div>
    </div>
    </div>    
{% endblock login %}

hello1/templates/hello1/signup.html
{% extends 'hello1/base.html' %}
<div class="container">
    {% block signup %}
    <div class="col-sm-6 mt-4">
        <h3>Registrations Form</h3>
        {% if messages %}
            {% for msg in messages %}
            <p {% if msg.tags %} class="alert alert-{{msg.tags}}" {% endif %}>{{msg}}</p>
            {% endfor %}
            {% endif %}
        <form action="" method="post" novalidate class="shadow-sm p-5">
            {% csrf_token %}
            {% for fm in form %}
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
            {% endfor %}    
        <input type="submit" value="Submit" class="btn btn-primary">
        {% if form.non_field_errors %} 
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}
        </form>
    {% endblock signup %}
</div>

hello1/templates/hello1/updatebook.html
{% extends 'hello1/base.html' %}
{% block content %}
<div class="container">
    <div class="p-2 m-2">
        <div class="col-lg-5 mx-auto">
            <h4 class="text-center alert alert-info">Bookshop</h4>
            <div class="card border-primary" style="width: 33rem;">
                <div class="card-body">
                  <h5 class="card-title">Update Book Details</h5>
                  <p class="card-text"> <form action="" method="POST" novalidate>
                    {% csrf_token %}
                    {% for fm in form %}
                     {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br>
                    {% endfor %}
                    <input class="btn btn-success" type="submit" value="Update">
                    <a class="btn btn-success" href="{% url 'addshow' %}">Back</a>
                </form></p>
                </div>
              </div>
        </div>
    </div>
</div>
{% endblock content %}